### ISSUE TITLE
bug: `show_no_change` is true by default

### ISSUE THREAD

**Issue by Eirmas** [exoego/esbuild-bundle-analyzer#74]
`show_no_change` seems to be true by default, but it says in the README that it should be false.

From the Github Actions output:
```
Run exoego/esbuild-bundle-analyzer@v1
  with:
    metafiles: dist/apps/project/stats.json
    show_details: false
    top_n_largest_paths: 0
    name: project
    analyze_directory: .analyzer
    include_extensions: .js,.cjs,.mjs
    percent_extra_attention: 20
    show_no_change: true
```

From config:
```
uses: exoego/esbuild-bundle-analyzer@v1
with:
  metafiles: 'dist/apps/project/stats.json'
  show_details: false
  top_n_largest_paths: 0
```
